# Generated by Django 3.1.2 on 2020-10-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('pk_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('pk_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('pk_tour', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('pk_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('tour_date', models.DateField()),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tors_app.customer')),
                ('fk_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tors_app.tour')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tors_app.status')),
            ],
        ),
    ]
